## Association Rule Mining (ARM)

#### Definition
Association Rule Mining is a technique used to discover relationships between items in a dataset.

It is mainly used in Market Basket Analysis.

---

#### Example
If a customer buys Bread → they may also buy Butter

---

#### Key Terms

1. Support
- It shows how frequently an item appears in dataset
- Formula:
  Support(A) = (Transactions containing A) / (Total Transactions)

2. Confidence
- It shows how often the rule is true
- Formula:
  Confidence(A → B) = Support(A ∪ B) / Support(A)

3. Lift
- It shows strength of rule
- Formula:
  Lift(A → B) = Confidence(A → B) / Support(B)

- Lift > 1 → Strong rule
- Lift = 1 → No relation
- Lift < 1 → Weak rule

---

#### Steps in Association Rule Mining

1. Collect transaction dataset
2. Find frequent itemsets using Apriori
3. Apply minimum support threshold
4. Generate rules using confidence
5. Evaluate rules using lift

---

#### Algorithm Used
- Apriori Algorithm (most common)

---

#### Advantages
- Helps in product recommendation
- Easy to understand
- Useful in business decision making

---

#### Disadvantages
- Computationally expensive
- Generates too many rules
- Needs proper threshold selection

In [4]:
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (0.24.0)
Requirement already satisfied: scipy>=1.16.3 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from mlxtend) (1.17.1)
Requirement already satisfied: numpy>=2.3.5 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from mlxtend) (2.4.4)
Requirement already satisfied: pandas>=2.3.3 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from mlxtend) (2.3.3)
Requirement already satisfied: scikit-learn>=1.8.0 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from mlxtend) (1.8.0)
Requirement already satisfied: matplotlib>=3.10.8 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from mlxtend) (3.10.9)
Requirement already satisfied: joblib>=1.5.2 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from pandas>=2.3.3->mlxtend) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from pandas>=2.3.3->mlxtend) (2026.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\vaishnavi giri\desktop\@gpp\internship\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [7]:
# Load dataset
df = pd.read_csv("groceries.csv")

df.head()

,Item(s),Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
0,4,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Convert each row into list (remove NaN values)

transactions = []

for i in range(len(df)):
    transactions.append([str(item) for item in df.iloc[i] if pd.notna(item)])

# Check first 5 transactions
transactions[:5]

[['4', 'citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'],
 ['3', 'tropical fruit', 'yogurt', 'coffee'],
 ['1', 'whole milk'],
 ['4', 'pip fruit', 'yogurt', 'cream cheese', 'meat spreads'],
 ['4',
  'other vegetables',
  'whole milk',
  'condensed milk',
  'long life bakery product']]

In [ ]:
# Apply Transaction Encoder
# used because to converts transactions into binary format which is required for apriori algorithm

te = TransactionEncoder()
te_data = te.fit(transactions).transform(transactions)

basket = pd.DataFrame(te_data, columns=te.columns_)

basket.head()

,1,10,11,12,13,14,15,16,17,18,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

## Apriori Algorithm

#### Definition
Apriori Algorithm is used in Association Rule Mining to find frequent itemsets and generate association rules using support, confidence, and lift.

---

### Basic Concept (Apriori Property)
If an itemset is frequent, then all of its subsets must also be frequent.

Example:
If {Milk, Bread} is frequent, then {Milk} and {Bread} must also be frequent.

---

#### Key Terms

1. Itemset
A collection of items (e.g., Milk, Bread)

2. Frequent Itemset
Itemset whose support is greater than minimum threshold

3. Support
Support(A) = (Transactions containing A) / (Total Transactions)

---

### Steps of Apriori Algorithm

Step 1: Find 1-itemsets
- Calculate support of each item
- Keep only those above minimum support

Step 2: Generate 2-itemsets
- Combine frequent 1-itemsets
- Calculate their support

Step 3: Pruning
- Remove itemsets with low support
- If subset is not frequent, discard full itemset

Step 4: Generate higher itemsets (3-itemsets, etc.)
- Repeat combine + support + prune

Step 5: Stop Condition
- Stop when no new itemsets are generated

Step 6: Generate Rules
- Create rules from frequent itemsets
- Calculate confidence and lift

---

#### Flow
Generate → Test → Prune → Repeat

---

#### Advantages
- Easy to understand
- Reduces search space using pruning
- Useful in market basket analysis

---

#### Disadvantages
- Slow for large datasets
- Requires multiple scans
- High memory usage

In [10]:
# Find frequent itemsets

frequent_items = apriori(basket, min_support=0.02, use_colnames=True)

frequent_items.head()

    support itemsets
0  0.219522      (1)
1  0.025013     (10)
2  0.167056      (2)
3  0.132079      (3)
4  0.102186      (4)

In [11]:
# Generate association rules

rules = association_rules(frequent_items, metric="lift", min_threshold=1)

rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(canned beer),(1),0.077682,0.219522,0.026436,0.340314,1.550250,1.0,0.009383,1.183105,0.384838,0.097634,0.154767,0.230370
1,(1),(canned beer),0.219522,0.077682,0.026436,0.120426,1.550250,1.0,0.009383,1.048597,0.454776,0.097634,0.046344,0.230370
2,(rolls/buns),(3),0.183935,0.132079,0.024301,0.132117,1.000287,1.0,0.000007,1.000044,0.000351,0.083304,0.000044,0.158052
3,(3),(rolls/buns),0.132079,0.183935,0.024301,0.183988,1.000287,1.0,0.000007,1.000065,0.000330,0.083304,0.000065,0.158052
4,(4),(other vegetables),0.102186,0.193493,0.020946,0.204975,1.059343,1.0,0.001173,1.014443,0.062395,0.076240,0.014237,0.156613

In [12]:
# Display important columns

rules[['antecedents','consequents','support','confidence','lift']]

,antecedents,consequents,support,confidence,lift
0,(canned beer),(1),0.026436,0.340314,1.550250
1,(1),(canned beer),0.026436,0.120426,1.550250
2,(rolls/buns),(3),0.024301,0.132117,1.000287
3,(3),(rolls/buns),0.024301,0.183988,1.000287
4,(4),(other vegetables),0.020946,0.204975,1.059343
...,...,...,...,...,...
137,"(whole milk, other vegetables)",(yogurt),0.022267,0.297554,2.132979
138,"(other vegetables, yogurt)",(whole milk),0.022267,0.512881,2.007235
139,(whole milk),"(other vegetables, yogurt)",0.022267,0.087147,2.007235
140,(yogurt),"(whole milk, other vegetables)",0.022267,0.159621,2.132979
141,(other vegetables),"(whole milk, yogurt)",0.022267,0.115081,2.054131